"""sprint_3_scheduling_and_leave

Revision ID: 18d82f8dca79
Revises: 08cbdf02a2cd
Create Date: 2026-05-15 00:56:37.740634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d82f8dca79'
down_revision: Union[str, Sequence[str], None] = '08cbdf02a2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('policy_key', sa.String(length=64), nullable=False),
    sa.Column('policy_value', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'policy_key', name='uq_company_policy_key')
    )
    with op.batch_alter_table('company_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_policies_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_policies_policy_key'), ['policy_key'], unique=False)

    op.create_table('leave_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('pto_total', sa.Float(), nullable=False),
    sa.Column('pto_used', sa.Float(), nullable=False),
    sa.Column('sick_total', sa.Float(), nullable=False),
    sa.Column('sick_used', sa.Float(), nullable=False),
    sa.Column('comp_earned', sa.Float(), nullable=False),
    sa.Column('comp_used', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'company_id', 'year', name='uq_leave_balance_employee_company_year')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balances_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_employee_id'), ['employee_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_requested', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)

    op.create_table('shift_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=False),
    sa.Column('shift_end', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_schedules_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_schedules_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_schedules_shift_date'), ['shift_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_schedules_shift_date'))
        batch_op.drop_index(batch_op.f('ix_shift_schedules_employee_id'))
        batch_op.drop_index(batch_op.f('ix_shift_schedules_company_id'))

    op.drop_table('shift_schedules')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_company_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balances_employee_id'))
        batch_op.drop_index(batch_op.f('ix_leave_balances_company_id'))

    op.drop_table('leave_balances')
    with op.batch_alter_table('company_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_policies_policy_key'))
        batch_op.drop_index(batch_op.f('ix_company_policies_company_id'))

    op.drop_table('company_policies')
    # ### end Alembic commands ###
